name: "order_srv"
mode: "dev"
ip: "127.0.0.1"
rpcPort: 8383
httpPort: 8093
version: "v0.0.1"
start_time: "2023-06-22"
machine_id: 3

log:
  level: "debug"
  filename: "order_service/log/order_srv.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "sf20020107"
  dbname: "alive_platform"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

consul:
  addr: "127.0.0.1:8500"

goods_service:
  name: goods_srv

repertory_service:
  name: repertory_service

rocketmq:
  addr: 127.0.0.1:9876
  group_id: order_srv
  topic:
    pay_timeout: platform_order_timeout
    repertory_rollback: platform_repertory_rollback